### ISSUE TITLE
The connection was lost

### ISSUE THREAD

**Issue by 91072437** [littleyoda/pysma#9]
Hallo,  Ich habe einen SUNNY TRIPOWER 10.0 SE, den ich über Webconnect eingerichtet hatte, und einen Home Manager2 über Speedwireem. Wenn ich mich über Webconnect mit dem SUNNY TRIPOWER 10.0 SE verbinde, habe ich das Problem, dass die Werte nur einmal gelesen werden. Dann geht das Plugin beim Webconnect auf Fehler aus. Die Werte von speedwireem kommen alle 10 Sekunden ohne Probleme. Ich habe das Plugin bereits neu installiert, ohne Erfolg. Hat jemand eine Idee, was das Problem ist? Die Protokolldatei befindet sich im Anhang.  Danke :-) [20241126_163616_257_SUNNY.log](https://github.com/user-attachments/files/17922141/20241126_163616_257_SUNNY.log)

**Comment by littleyoda** [comment]
Hi

leider habe ich mit LoxBerry keine Erfahrung. Das Plugin dafür habe ich auch nicht geschrieben.
Wenn ich es richtig stehe, bekommt er aber keine Verbindung zu mqtt-Server.
 

Traceback (most recent call last):
  File "/opt/loxberry/bin/plugins/sma2loxone/pysma2mqtt.py", line 187, in main_loop
    await client.publish(
  File "/usr/local/lib/python3.11/dist-packages/aiomqtt/client.py", line 105, in decorated
    return await method(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiomqtt/client.py", line 440, in publish
    raise MqttCodeError(info.rc, "Could not publish message")
aiomqtt.exceptions.MqttCodeError: [code:4] The client is not currently connected.

**Comment by littleyoda** [comment]
Keine Rückmeldung => Close
